NfqAkademija\FrontendBundle\Entity\Image:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        fileName:
            type: string
            length: 255
        filePath:
            type: string
            length: 255
        createdDate:
            type: datetime
    lifecycleCallbacks: {  }
