nfq_akademija_user:
    resource: "@NfqAkademijaUserBundle/Resources/config/routing.yml"
    prefix:   /

nfq_akademija_frontend:
    resource: "@NfqAkademijaFrontendBundle/Resources/config/routing.yml"
    prefix:   /

oneup_uploader:
    resource: .
    type: uploader