nfq_akademija_frontend_index:
    path:     /
    defaults: { _controller: NfqAkademijaFrontendBundle:DisplayHandler:index }

nfq_akademija_frontend_ajax_scroll:
    path:     /ajax_scroll/{start}
    defaults: { _controller: NfqAkademijaFrontendBundle:DisplayHandler:ajaxScroll, start: 0 }

nfq_akademija_frontend_rating_like:
    path:     /rate_like/{photo_id}
    defaults: { _controller: NfqAkademijaFrontendBundle:DisplayHandler:ajaxRateLike }

nfq_akademija_frontend_rating_dislike:
    path:     /rate_dislike/{photo_id}
    defaults: { _controller: NfqAkademijaFrontendBundle:DisplayHandler:ajaxRateDislike }

nfq_akademija_frontend_upload:
    path:     /upload
    defaults: { _controller: NfqAkademijaFrontendBundle:UploaderHandler:index }

nfq_akademija_frontend_upload_ajax:
    path:     /ajax_upload
    defaults: { _controller: NfqAkademijaFrontendBundle:UploaderHandler:upload }