nfq_akademija_frontend_index:
    path:     /
    defaults: { _controller: NfqAkademijaFrontendBundle:DisplayHandler:index }

nfq_akademija_frontend_upload:
    path:     /upload
    defaults: { _controller: NfqAkademijaFrontendBundle:UploaderHandler:index }

nfq_akademija_frontend_upload_ajax:
    path:     /ajax_upload
    defaults: { _controller: NfqAkademijaFrontendBundle:UploaderHandler:upload }

test:
    resource: "@NfqAkademijaFrontendBundle/Controller/PhotoController.php"
    prefix:   /
    type:     annotation

test1:
    resource: "@NfqAkademijaFrontendBundle/Controller/TagsController.php"
    prefix:   /
    type:     annotation

