parameters:
    photo_uploader.class: NfqAkademija\FrontendBundle\Service\PhotoUploader
#    upload_listener.class: NfqAkademija\FrontendBundle\EventListener\UploadListener

services:
    photo_uploader:
        class:        "%photo_uploader.class%"
        arguments: [%kernel.root_dir%, @form.factory]

    nfqakademija_frontend.upload_listener:
        class:      NfqAkademija\FrontendBundle\EventListener\UploadListener
        arguments:  [@doctrine]
        tags:
          - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }