parameters:
    photo_uploader.class: NfqAkademija\FrontendBundle\Service\PhotoUploader
    image_worker.class: NfqAkademija\FrontendBundle\Service\ImageWorker
    form_errors_serializer.class: NfqAkademija\FrontendBundle\Service\FormErrorsSerializer
    display_photo.class: NfqAkademija\FrontendBundle\Service\DisplayPhoto

services:
    photo_uploader:
        class:        "%photo_uploader.class%"
        arguments: [%kernel.root_dir%, @form.factory, @doctrine.orm.entity_manager]
    image_worker:
        class: "%image_worker.class%"
    form_errors_serializer:
        class: "%form_errors_serializer.class%"
    display_photo:
        class: "%display_photo.class%"
        arguments: [@doctrine.orm.entity_manager]