#src/NfqAkademija/NfqAkademijaFrontendBundle/Resources/config/validation.yml
NfqAkademija\FrontendBundle\Entity\Photo:
    properties:
        fileName:
            - NotBlank:
                message: "Nepasirinktas paveikslėlis."
            - Image:
                mimeTypes: [image/jpeg, image/png]
                mimeTypesMessage: "Neteisingas failo tipas."
                minWidth: 300
                minWidthMessage: "Paveikslėlio plotis per mažas."
                minHeight: 300
                minHeightMessage: "Paveikslėlio aukštis per mažas."
            - File:
                maxSize: 5242880
                maxSizeMessage: "Paveikslėlis per didelis."
        title:
            - NotBlank:
                message: "Nuotraukos aktraštė patikta tuščia."
            - Length:
                  min: 10
                  minMessage: "Paveikslėlio aptraštė per trumpa, turi būti mažiausiai {{ limit }} simbolių."
                  max: 100
                  minMessage: "Paveikslėlio aptraštė per ilga, turi būti daugiausiai {{ limit }} simbolių."