parameters:
    oauth_user_provider.class: NfqAkademija\UserBundle\Service\FOSUserProvider

services:
    oauth_user_provider:
        class: "%oauth_user_provider.class%"
        arguments: [@fos_user.user_manager,{facebook: facebookId}]